version: "3.9"

services:
  redis:
    image: redis:7
    restart: always

  api:
    build: ./music-backend
    restart: always
    command: gunicorn -b 0.0.0.0:5000 app:app
    env_file: .env.cloud
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    depends_on:
      - redis

  worker:
    build: ./music-backend  
    restart: always
    command: celery -A tasks worker --loglevel=info
    env_file: .env.cloud
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    depends_on:
      - redis

  frontend:
    build: ./music-frontend
    restart: always

  caddy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - frontend
      - api